/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  MCE.UID.CPP*
*/

// Makmake-generated uid source file
#include <E32STD.H>
#pragma data_seg(".E32_UID")
__WINS_UID(0x10000079,0x100039ce,0x100058c5)
#pragma data_seg()
